---

#My Playbook to configure Ansible server, Webserver and DB server

- name: "COMMON PACKAGE | Configure Common packeges in all servers"
  hosts: all
  become: True
  gather_facts: False
  
  roles:
  - common
  
  
- name: "DB SERVER | Configure DB server"
  hosts: dbservers 
  remote_user: deploy
  become: True
  gather_facts: True

  roles:
  - db

- name: "WEB SERVER | Configure Web server"
  hosts: webservers
  remote_user: deploy
  become: True
  gather_facts: False

  roles:
  - web
...
