---

#My Playbook to configure wWebserver and DB server

- name: "Configure Common packeges in all servers"
  hosts: all
  remote_user: deploy
  become: True
  gather_facts: False
  
  roles:
  - common
  
- name: " Configure DB server"
  hosts: dbservers 
  remote_user: deploy
  become: True
  gather_facts: True

  roles:
  - db

- name: "Configure Web server"
  hosts: webservers
  remote_user: deploy
  become: True
  gather_facts: True

  roles:
  - web
...
