Vagrant.configure("2") do |config|
  
  config.vm.define "ansible", primary: true do |ansible|
   ansible.vm.box = "centos/7"
   ansible.vm.provision :shell, path: "bootstrap.sh"
   ansible.vm.hostname = "ansible"
   ansible.vm.network "private_network", ip: "172.31.76.173"
  end

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "172.31.76.174"
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "172.31.76.175"
  end 
end
