Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"
  
  config.vm.define "ansible", primary: true do |ansible|
   ansible.vm.box = "centos/7"
   ansible.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
  end
  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
  end 
end
