---
# tasks file for db

- name: "Install MariaDB packages"
  yum: state=present name={{ item }}
  with_items:
    - mariadb
    - mariadb-server
  notify: Restart MariaDB 
  
  
 - name: "Create a Database with name '{{ db_name }}'"
   mysql_db: name="{{ db_name }}" state=present
   
 - name: "Create a Database user with name '{{ db_user }}' for the Database '{{ db_name }}'"
   mysql_user:
     db: {{ db_name }}
     name: {{ db_user }}
     password: {{ db_password}}
     priv: '*.*:ALL'
     state: present
   
...
