---
# tasks file for db

- name: "Install MariaDB packages"
  yum: state=present name={{ item }}
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
  notify: Restart MariaDB 

- name: "Firewall | Enable MySQL  ports in firewall"
  firewalld: zone=public service="{{ item }}" permanent=true state=enabled
  with_items:
    - mysql
  notify: Reload Firewalld

- name: Start mariadb service
  service: name=mariadb state=started 
  
- name: "Create a Database with name {{ db_name }}"
  mysql_db: name={{ db_name }} state=present
   
- name: "Create a Database user with name {{ db_user }} for the Database {{ db_name }}"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: "%"

- name: Give hostall permission to mysql user
  mysql_user: name={{ db_user }} host_all=yes
...
