---
# tasks file for web

- name: "Apache | Install Apache packages"
  yum: 
    name: httpd
    state: present
  notify: Restart Apache

- name: "Apache | Include variables of Database Server in Webserver"
  include_vars: ../../roles/db/vars/main.yml
    
- name: "Apache | Create virtualhost file" 
  template: src=vhost.conf.j2 dest=/etc/httpd/vhost.d/web.conf

- name: "Apache | Creating Documentroot for the site"
  file:
    path: "{{ app_path }}"
    state: directory
    mode: 0755
    owner: apache
    group: apache

- name: " Apache | Cheching before wordpress install"
  stat: path={{ app_path }}/wp-content/uploads
  register: wordpress_install
   
#- name: "Copy index.html"
#  template: src=index.html.j2 dest=/var/www/html/index.html
  
- name: "PHP | Install PHP packages"
  yum: state=present name={{ item }}
  with_items:
    - php
    - php-common
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mysqlnd
    - php-pdo
    - php-pgsql
    - php-process
    - php-recode
    - php-soap
    - php-xml
  notify: Restart Apache

#- name: "Copy PHP Info"
#  template: src=info.php.j2 dest=/var/www/html/info.php

- name: "Wordpress | Wordpress related tasks"
  block:
  
    - debug: msg="Wordpress | Download Wordpress"
    - unarchive: remote_src=yes src={{ LATEST_WP_URL }} dest={{ DOWNLOAD_PATH }}

#    - debug: msg="Wordpress | Rename download folder"
#    - command: cd /tmp;mv "{{ DOWNLOAD_PATH }}"/wordpress* "{{ DOWNLOAD_PATH }}"/wordpress

    - debug: msg="Application | Copy wordpress files to the application document root"
    - command: rsync -avP /tmp/wordpress/ "{{ app_path }}"
  
    - debug: msg="Application | Create uploads folder for application"
    - command: mkdir "{{ app_path }}"/wp-content/uploads
  
    - debug: msg="Application | Create Database configuration file for the site"
    - template: src=wp-config.php.j2 dest={{ app_path }}/wp-config.php
  
    - debug: msg="Application | Permission set for the documentroot"
    - file:
        path: "{{ app_path }}"
        state: directory
        mode: 0755
        owner: apache
        group: apache
        recurse: yes
      
  when: wordpress_install.stat.exists == False
...
