---
# tasks file for common

- name: "SELINUX | Manege SELinux"
  selinux: policy=targeted state=permissive

- name: "COMMON PACKAGES | Install Common Packages"
  yum: state=present name={{ item }}
  with_items:
    - ntp
    - wget
    - unzip
  
- name: "WELCOME BANNER | Update Banner"
  template: src=motd.j2 dest=/etc/motd
