---
# tasks file for common

- name: "Manege SELinux"
  selinux: policy=targeted state=permissive

- name: "Install Common Packages"
  yum: state=present name={{ item }}
  with_items:
    - ntp
    - wget
  
- name: "Update Banner"
  template: src=motd.j2 dest=/etc/motd
