---
# vars file for web

######################################
# Virtual Host configuration option
######################################
website_name: worldofjoy.com
virtualhost_domain: "{{ website_name | replace('.','_') }}"

######################################
# Application setup option
######################################
app_path: /var/www/html

######################################
# Wordpress configuration option
######################################
LATEST_WP_URL: https://wordpress.org/latest.tar.gz
DOWNLOAD_PATH: /tmp/


