---
# vars file for web

######################################
# Virtual Host configuration option
######################################
virtualhost_domain: worldofjoy.com

######################################
# Application setup option
######################################
app_path: /var/www/html/{{ virtualhost_domain|replace('.','_')}}



######################################
# Database server conection
######################################
db_server: "{{ hostvars[groups['dbservers'][0]]['ansible_default_ipv4']['address']}}"

######################################
# Wordpress configuration option
######################################
LATEST_WP_URL: https://wordpress.org/latest.tar.gz
DOWNLOAD_PATH: /tmp/(date + '%Y%m%d')


