---
# vars file for web

######################################
# Virtual Host configuration option
######################################
website_name: worldofjoy.com
virtualhost_domain: "{{ website_name | replace('.','_') }}"


######################################
# Application setup option
######################################
app_path: /var/www/html/



######################################
# Database server conection (( moved this variable into db role to pickup db ip ))
######################################
#db_server: "{{ hostvars[groups['dbservers'][0]]['ansible_ssh_hostname'] }}"
#db_server: 172.18.56.182
#db_server: "{{ hostvars['db']['ansible_all_ipv4_addresses'] }}"

######################################
# Wordpress configuration option
######################################
LATEST_WP_URL: https://wordpress.org/latest.tar.gz
DOWNLOAD_PATH: /tmp/


